language: php

sudo: false

matrix:
    include:
        - php: 5.4
        - php: 5.5
    fast_finish: true

env:
    global:
        - deps=no

before_install:
    - composer self-update
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php -i; fi;

install:
    - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;

script:
    - if [ "$deps" = "no" ]; then echo -e "\\nRunning tests"; phpunit || (echo -e "\\e[41mKO\\e[0m tty group" && $(exit 1)); fi;

